In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import ks_2samp

## 活動選択（コルモゴロフ–スミルノフ検定）

In [2]:
data = pd.read_csv('Row Data.csv')

In [3]:
wave0 = data.loc[:,"1_q8_2_1":"1_q8_2_12"].fillna(0)
wave1 = data.loc[:,"1_q6_2_1":"1_q6_2_12"].fillna(0)
wave2 = data.loc[:,"2_q4_2_1":"2_q4_2_12"].fillna(0)
wave3 = data.loc[:,"3_q4_2_1":"3_q4_2_12"].fillna(0)

In [4]:
print(wave0.values)

[[0. 0. 0. ... 0. 0. 0.]
 [4. 0. 1. ... 1. 0. 2.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [6. 0. 0. ... 0. 0. 2.]
 [6. 0. 0. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]]


In [5]:
Labels = ["Commuting","Pick-up and drop-off","Hospital visit",
         "Shopping for food and necessities","Get take-out food at restaurants",
         "Shopping for others (excluding food, necessities, and take-out food)","Eat and drink for socializing","Eat and drink for others",
         "Indoor amusement (movie, etc.)","Individual outdoor activity","Group outdoor activity",
         "Use essential services (bank, etc.)"]

In [20]:
with open ('ValidationI.csv','a') as f:
    for i in range(1,13):
        Pvalue = []
        W0 = wave0['1_q8_2_'+str(i)].values
        W1 = wave1['1_q6_2_'+str(i)].values
        W2 = wave2['2_q4_2_'+str(i)].values
        W3 = wave3['3_q4_2_'+str(i)].values

        Pvalue.append(stats.ks_2samp(W0,W1).pvalue)
        Pvalue.append(stats.ks_2samp(W0,W2).pvalue)
        Pvalue.append(stats.ks_2samp(W0,W3).pvalue)
        f.write(str(Pvalue[0])+','+str(Pvalue[1])+','+str(Pvalue[2])+'\n')
        if min(Pvalue) < 0.05:
            print('a'+str(i)+':'+Labels[i-1])

a1:Commuting
a4:Shopping for food and necessities
a7:Eat and drink for socializing
a8:Eat and drink for others
a9:Indoor amusement (movie, etc.)


## t検定

In [33]:
LC = pd.read_csv('LC.csv')

In [34]:
Features = ['gender','elder','D23','dif','hel','ful','veh','nee','pb']
#Activities = ['a1','a2','a3','a4','a5','a6','a7','a8','a8','a9','a10','a11','a12']
Activities = ['a1','a4','a7','a8','a9']

In [35]:
wave0 = LC[LC['wave'] == 0].reset_index(drop=True)
wave1 = LC[LC['wave'] == 1].reset_index(drop=True)
wave2 = LC[LC['wave'] == 2].reset_index(drop=True)
wave3 = LC[LC['wave'] == 3].reset_index(drop=True)

In [38]:
with open ('ValidationII.csv','a') as f:
    for a in Activities:
        for x in Features:
            Pvalue = []
            W00 = wave0[wave0[x] == 0][a].values # wave0における、特徴xを持たない人がアクティビティaの日数選択状況
            W10 = wave1[wave1[x] == 0][a].values
            W20 = wave2[wave2[x] == 0][a].values
            W30 = wave3[wave3[x] == 0][a].values
            W01 = wave0[wave0[x] == 1][a].values
            W11 = wave1[wave1[x] == 1][a].values
            W21 = wave2[wave2[x] == 1][a].values
            W31 = wave3[wave3[x] == 1][a].values

            Pvalue.append(stats.ttest_ind(W00,W01,equal_var = False).pvalue)
            Pvalue.append(stats.ttest_ind(W10,W11,equal_var = False).pvalue)
            Pvalue.append(stats.ttest_ind(W20,W21,equal_var = False).pvalue)
            Pvalue.append(stats.ttest_ind(W30,W31,equal_var = False).pvalue)
            
            f.write(str(stats.ttest_ind(W00,W01,equal_var = False).statistic)+',')
            f.write(str(stats.ttest_ind(W00,W01,equal_var = False).pvalue)+',')
            f.write(str(stats.ttest_ind(W10,W11,equal_var = False).statistic)+',')
            f.write(str(stats.ttest_ind(W10,W11,equal_var = False).pvalue)+',')
            f.write(str(stats.ttest_ind(W20,W21,equal_var = False).statistic)+',')
            f.write(str(stats.ttest_ind(W20,W21,equal_var = False).pvalue)+',')
            f.write(str(stats.ttest_ind(W30,W31,equal_var = False).statistic)+',')
            f.write(str(stats.ttest_ind(W30,W31,equal_var = False).pvalue)+',')
            
            if max(Pvalue) < 0.05:
                print(a+':'+x)
        f.write('\n')

a1:ful
a1:nee
a1:pb
a4:dif
a9:hel
